CXX = g++
CXXFLAGS = -Wall -Werror -Wextra -pedantic -std=c++17 -g -fsanitize=address
LDFLAGS =  -fsanitize=address

SRC = Symbol.cc Tools.cc Alphabet.cc Chain.cc FA.cc State.cc ClientFA.cc
OBJ = $(SRC:.cc=.o)
EXEC = NFA2DFA

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CXX) $(LDFLAGS) -o $@ $(OBJ) $(LBLIBS)

clean:
	rm -rf $(OBJ) $(EXEC)